### ISSUE TITLE
Incorrect form action link?

### ISSUE THREAD

**Issue by edevil** [Baeldung/spring-security-registration#110]
I've noticed that `registration.html` has a form with an action URL of `/`. Shouldn't this be `/user/registration`?

I've tried to incorporate the registration flow in a demo and the form post ended up nowhere since no controller was listening for POSTs on `/`.

**Comment by lor6** [comment]
This is because the form is submitted using Ajax: https://github.com/Baeldung/spring-security-registration/blob/master/src/main/resources/templates/registration.html#L104 and the register() function is added to the form here: https://github.com/Baeldung/spring-security-registration/blob/master/src/main/resources/templates/registration.html#L65
