### ISSUE TITLE
javax.mail.AuthenticationFailedException: 535 AUTH failed

### ISSUE THREAD

**Issue by CoolR7** [Baeldung/spring-security-registration#45]
Hi Team

I am getting the below exception after submitting the button on the registration page.

web - 2017-10-10 23:14:06,669 [tomcat-http--8] ERROR o.b.w.e.RestResponseEntityExceptionHandler - 500 Status Code
o.s.m.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535 AUTH failed

	at o.s.m.j.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:424)
	at o.s.m.j.JavaMailSenderImpl.send(JavaMailSenderImpl.java:307)
	at o.s.m.j.JavaMailSenderImpl.send(JavaMailSenderImpl.java:296)
	at o.b.r.l.RegistrationListener.confirmRegistration(RegistrationListener.java:43)
	at o.b.r.l.RegistrationListener.onApplicationEvent(RegistrationListener.java:34)
	... 90 frames truncated
Caused by: j.m.AuthenticationFailedException: 535 AUTH failed

Below is the content of the email.properties file
spring.mail.properties.mail.host=smtp.gmail.com
spring.mail.properties.mail.username=XYZ@gmail.com
spring.mail.properties.mail.password=********
spring.mail.properties.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback =false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

Could you please help me to figure out to resolve this issue.

**Comment by eugenp** [comment]
Thanks for the note @CoolR7 - looking into it.

**Comment by pivovarit** [comment]
@CoolR7 try using `application.properties` instead of the deprecated `email.properties`, does that help?

**Comment by eugenp** [comment]
Hey @CoolR7  - I had a closer look at this issue here, and I wanted to follow up. 
So, it looks like your SMTP server isn't working. That can be happening for a wide range of reasons (especially since you're using Gmail). And of course there's documentation about most of these reasons online. 
But, the point here is - that's mostly outside of the scope of this codebase. The idea is - in order to be able to send emails, you need to have a working, valid SMTP server set up. 
Hope that helps. 
Cheers, 
Eugen.

**Comment by CoolR7** [comment]
@eugenp  Thanks for looking into the issue.
